Repository NOAA-EMC/GDASApp, pull requests merged in 2022-06, with the labels that each got.

#63 Update YAML changes and some bug fixes
  modulefiles/GDAS/orion.lua
  parm/atm/obs/lists/gdas_prototype.yaml
  ush/examples/run_jedi_exe/3dhofx.yaml
  ush/examples/run_jedi_exe/3dvar.yaml
  ush/examples/run_jedi_exe/4dhofx.yaml
  ush/run_jedi_exe.py
  ush/ufsda/misc_utils.py
  ush/ufsda/stage.py
  ush/ufsda/yamltools.py
Labels: orion-RT-Passed, hera-RT-Passed

#61 Update sondes.yaml
  parm/atm/obs/config/sondes.yaml
Labels: hera-RT-Passed, orion-RT-Running

#64 Make interpolation method configurable
  parm/atm/obs/config/amsua_n19.yaml
  parm/atm/obs/config/sondes.yaml
  ush/examples/run_jedi_exe/3dhofx.yaml
  ush/examples/run_jedi_exe/3dvar.yaml
  ush/examples/run_jedi_exe/4dhofx.yaml
  ush/run_jedi_exe.py
Labels: orion-RT-Passed, hera-RT-Passed

#62 Run step for soca (grid generation and 3dvar fgat)
  parm/soca/berror/parametric_stddev_b.yaml
  parm/soca/berror/saber_block_identity.yaml
  parm/soca/gridgen/gridgen.yaml
  parm/soca/obs/config/adt_j3.yaml
  parm/soca/obs/config/sst_noaa19_l3u.yaml
  parm/soca/obs/obs_list.yaml
  parm/soca/variational/3dvarfgat.yaml
  parm/templates/stage.yaml
  scripts/exgdas_global_marine_analysis_prep.py
  scripts/exgdas_global_marine_analysis_run.sh
  test/soca/CMakeLists.txt
  test/soca/runtime_vars.sh
  test/soca/static.sh
  test/soca/test_prep.sh
  test/soca/test_run.sh
  test/soca/test_utils.sh
  ush/ufsda/stage.py
  ush/ufsda/ufs_yaml.py
Labels: orion-RT-Passed, hera-RT-Running

#58 Add sample run_jedi_exe YAMLs to repo
  ush/examples/run_jedi_exe/3dhofx.yaml
  ush/examples/run_jedi_exe/3dvar.yaml
  ush/examples/run_jedi_exe/4dhofx.yaml
Labels: orion-RT-Passed, hera-RT-Passed
