Repository NOAA-EMC/GDASApp, pull requests merged in 2022-11, with the labels that each got.

#175 Minor changes to get cycling going for aerosol DA
  parm/aero/berror/staticb_bump_aero.yaml
  parm/aero/obs/lists/gdas_aero_prototype.yaml
  parm/aero/variational/3dvar_gfs_aero.yaml
Labels: AeroDA

#170 Feature/gsibec
  build.sh
  parm/atm/berror/staticb_gsibec.yaml
  ush/examples/run_jedi_exe/3dvar_hera.yaml
  ush/examples/run_jedi_exe/3dvar_orion.yaml
  ush/run_jedi_exe.py
  ush/ufsda/stage.py
Labels: orion-RT-Passed, hera-RT-Passed

#145 Add YAML files for land DA
  parm/atm/hofx/hofx4d.yaml
  parm/land/hofx/hofx_nomodel.yaml
  parm/land/letkfoi/letkfoi.yaml
  parm/land/obs/config/adpsfc_snow.yaml
  parm/land/obs/config/ghcn_snow.yaml
  parm/land/obs/config/ims_snow.yaml
  parm/land/obs/lists/gdas_land_prototype.yaml
  ush/ufsda/yamltools.py
Labels: landDA

#176 Switch to reading a history file for the IC's
  scripts/exgdas_global_marine_analysis_prep.py
  scripts/exgdas_global_marine_analysis_run.sh
  test/CMakeLists.txt
  test/soca/CMakeLists.txt
  test/soca/fix/MOM_input
  test/soca/test_prep.sh
  test/soca/test_run.sh
Labels: orion-RT-Passed, hera-RT-Passed

#185 Make the soca run ctest work again
  ush/ufsda/yamltools.py
Labels: orion-RT-Passed, hera-RT-Passed

#178 adding sfcship test
  test/CMakeLists.txt
  test/soca/CMakeLists.txt
  test/testinput/bufr_sfcships.yaml
  test/testinput/bufr_sfcshipsu.yaml
Labels: orion-RT-Passed, hera-RT-Passed

#188 Fix to the cmake error msg when building
  test/soca/CMakeLists.txt
Labels: orion-RT-Passed, hera-RT-Passed

#189 Adding bufr2ioda test output to r2d2 database in soca test
  test/soca/CMakeLists.txt
  test/soca/create_obsdb.py
Labels: orion-RT-Passed, hera-RT-Passed

#195 Make cloning JCSDA test data repositories optional
  CMakeLists.txt
  build.sh
Labels: orion-RT-Passed, hera-RT-Passed

#186 Modify the yamltools to enable for generating yaml file for land DA.
  ush/ufsda/yamltools.py
Labels: orion-RT-Passed, hera-RT-Passed

#193 Feature/soca ana prep update
  parm/soca/obs/config/bufr_dbuoyprof.yaml
  parm/soca/obs/config/bufr_mbuoybprof.yaml
  parm/soca/obs/config/bufr_sfcships.yaml
  parm/soca/obs/config/bufr_sfcshipsu.yaml
  parm/soca/obs/config/icec_emc.yaml
  parm/soca/obs/config/icefb_gdr.yaml
  parm/soca/obs/config/salt_profile_fnmoc.yaml
  parm/soca/obs/config/sss_smap.yaml
  parm/soca/obs/config/temp_profile_fnmoc.yaml
  parm/soca/obs/obs_list.yaml
Labels: orion-RT-Passed, hera-RT-Passed

#190 Fetch obs from P1D and PT10M
  .github/workflows/unittests.yaml
  parm/soca/berror/soca_bump_C_split.yaml
  parm/soca/berror/soca_setcorscales.yaml
  parm/soca/variational/3dvarfgat.yaml
  test/CMakeLists.txt
  test/soca/CMakeLists.txt
  test/soca/test_prep.sh
  ush/ufsda/stage.py
Labels: orion-RT-Passed, hera-RT-Passed

#206 parted out dbuoyprof and mbuoybprof salt and temp in soca tests
  parm/soca/obs/config/salt_bufr_dbuoyprof.yaml
  parm/soca/obs/config/salt_bufr_mbuoybprof.yaml
  parm/soca/obs/config/temp_bufr_dbuoyprof.yaml
  parm/soca/obs/config/temp_bufr_mbuoybprof.yaml
  test/CMakeLists.txt
  test/soca/CMakeLists.txt
  test/soca/create_obsdb.py
  test/testinput/salt_bufr_dbuoyprof.yaml
  test/testinput/salt_bufr_mbuoybprof.yaml
  test/testinput/temp_bufr_dbuoyprof.yaml
  test/testinput/temp_bufr_mbuoybprof.yaml
Labels: orion-RT-Passed, hera-RT-Passed

#210 Reorg of where soca is staged/run
  parm/templates/stage.yaml
  scripts/exgdas_global_marine_analysis_prep.py
  test/soca/CMakeLists.txt
  test/soca/runtime_vars.sh
  test/soca/test_prep.sh
  test/soca/test_run.sh
  ush/ufsda/disk_utils.py
  ush/ufsda/stage.py
Labels: orion-RT-Passed, hera-RT-Passed

#207 Add a python script to create a pseudo ensemble for snow DA
  modulefiles/GDAS/hera.lua
  modulefiles/GDAS/orion.lua
  test/CMakeLists.txt
  test/land/CMakeLists.txt
  test/land/create_bkg_ens.sh
  ush/land/letkf_create_ens.py
Labels: orion-RT-Passed, hera-RT-Passed

#214 Bugfix for when testrun dir does not yet exist
  test/land/create_bkg_ens.sh
Labels: hera-RT-Passed, orion-RT-Running

#212 Have the CI cron job load modules from PR
  ci/driver.sh
  ci/run_ci.sh
Labels: orion-RT-Passed, hera-RT-Passed
