Repository NOAA-EMC/GDASApp, pull requests merged in 2022-10, with the labels that each got.

#163 A few adjustment to run the marine DA in the gw
  .gitignore
  parm/soca/variational/3dvarfgat.yaml
  scripts/exgdas_global_marine_analysis_prep.py
  scripts/exgdas_global_marine_analysis_run.sh
  test/soca/CMakeLists.txt
  test/soca/runtime_vars.sh
  test/soca/test_prep.sh
Labels: hera-RT-Passed, orion-RT-Failed

#134 Fixed variable list and added analysis increment.
  parm/aero/variational/3dvar_gfs_aero.yaml
Labels: AeroDA

#168 Add bufr2ioda ctest for marine obs profiles
  test/CMakeLists.txt
  test/soca/CMakeLists.txt
  test/testinput/bufr_dbuoy.yaml
  test/testinput/bufr_mbuoyb.yaml
  test/testinput/bufr_tesac.yaml
  test/testinput/bufr_trkob.yaml
Labels: orion-RT-Passed, hera-RT-Passed
