Repository NOAA-EMC/GDASApp, pull requests merged in 2022-12, with the labels that each got.

#208 Add in scripts to update repository hashes and to drive update script; return to develop branches for develop
  CMakeLists.txt
  ci/run_ci.sh
  ci/stable_driver.sh
  ci/stable_mark.sh
Labels: orion-RT-Failed, hera-RT-Failed

#211 Feature/marine obs yaml files
  parm/soca/obs/config/adt_3a_egm2008.yaml
  parm/soca/obs/config/adt_3b_egm2008.yaml
  parm/soca/obs/config/adt_6a_egm2008.yaml
  parm/soca/obs/config/adt_c2_egm2008.yaml
  parm/soca/obs/config/adt_coperl4.yaml
  parm/soca/obs/config/adt_j2_egm2008.yaml
  parm/soca/obs/config/adt_j3_egm2008.yaml
  parm/soca/obs/config/adt_sa_egm2008.yaml
  parm/soca/obs/config/icec_nsidc_nh.yaml
  parm/soca/obs/config/icec_nsidc_sh.yaml
  parm/soca/obs/config/icec_ssmis_f17_north.yaml
  parm/soca/obs/config/icec_ssmis_f17_south.yaml
  parm/soca/obs/config/icec_ssmis_f18_north.yaml
  parm/soca/obs/config/icec_ssmis_f18_south.yaml
  parm/soca/obs/config/icefb_gdr.yaml
  parm/soca/obs/config/oc_aqua.yaml
  parm/soca/obs/config/oc_dineof3.yaml
  parm/soca/obs/config/oc_noaa20.yaml
  parm/soca/obs/config/oc_snpp.yaml
  parm/soca/obs/config/salt_profile_fnmoc_godas.yaml
  parm/soca/obs/config/salt_profile_wod.yaml
  parm/soca/obs/config/sss_smap_jpl.yaml
  parm/soca/obs/config/sss_smos.yaml
  parm/soca/obs/config/sss_smos_esa.yaml
  parm/soca/obs/config/sss_trak_fnmoc.yaml
  parm/soca/obs/config/sst_amsr2_l3u.yaml
  parm/soca/obs/config/sst_drifter.yaml
  parm/soca/obs/config/sst_gmi_l3u.yaml
  parm/soca/obs/config/sst_metopa_l3u_so025.yaml
  parm/soca/obs/config/sst_metopb_l3u_so025.yaml
  parm/soca/obs/config/sst_metopc_l3u_so025.yaml
  parm/soca/obs/config/sst_noaa18_l3u_so025.yaml
  parm/soca/obs/config/sst_noaa19_l3u_so025.yaml
  parm/soca/obs/config/sst_ostia.yaml
  parm/soca/obs/config/sst_ship_fnmoc.yaml
  parm/soca/obs/config/sst_trak_fnmoc.yaml
  parm/soca/obs/config/sst_viirs_n20_l3u_so025.yaml
  parm/soca/obs/config/sst_viirs_npp_l3u_so025.yaml
  parm/soca/obs/config/sst_windsat_l3u.yaml
  parm/soca/obs/config/temp_profile_fnmoc_godas.yaml
  parm/soca/obs/config/temp_profile_wod.yaml
Labels: orion-RT-Passed, hera-RT-Passed

#220 SOCA bugfix
  parm/soca/berror/saber_blocks.yaml
  parm/soca/berror/soca_bump_C_split.yaml
  parm/soca/variational/3dvarfgat.yaml
  scripts/exgdas_global_marine_analysis_prep.py
Labels: orion-RT-Passed, hera-RT-Passed

#216 Add IMS preprocessing code to GDASApp
  CMakeLists.txt
  build.sh
  test/land/CMakeLists.txt
  test/land/test_imsproc.sh
Labels: orion-RT-Passed, hera-RT-Passed

#236 Conversion of soca yamls to g-w conventions
  parm/soca/obs/config/adt_3a_egm2008.yaml
  parm/soca/obs/config/adt_3b_egm2008.yaml
  parm/soca/obs/config/adt_6a_egm2008.yaml
  parm/soca/obs/config/adt_c2_egm2008.yaml
  parm/soca/obs/config/adt_coperl4.yaml
  parm/soca/obs/config/adt_j2_egm2008.yaml
  parm/soca/obs/config/adt_j3_egm2008.yaml
  parm/soca/obs/config/adt_sa_egm2008.yaml
  parm/soca/obs/config/bufr_sfcships.yaml
  parm/soca/obs/config/bufr_sfcshipsu.yaml
  parm/soca/obs/config/icec_nsidc_nh.yaml
  parm/soca/obs/config/icec_nsidc_sh.yaml
  parm/soca/obs/config/icec_ssmis_f17_north.yaml
  parm/soca/obs/config/icec_ssmis_f17_south.yaml
  parm/soca/obs/config/icec_ssmis_f18_north.yaml
  parm/soca/obs/config/icec_ssmis_f18_south.yaml
  parm/soca/obs/config/icefb_gdr.yaml
  parm/soca/obs/config/oc_aqua.yaml
  parm/soca/obs/config/oc_dineof3.yaml
  parm/soca/obs/config/oc_noaa20.yaml
  parm/soca/obs/config/oc_snpp.yaml
  parm/soca/obs/config/salt_bufr_dbuoyprof.yaml
  parm/soca/obs/config/salt_bufr_mbuoybprof.yaml
  parm/soca/obs/config/salt_profile_fnmoc_godas.yaml
  parm/soca/obs/config/salt_profile_wod.yaml
  parm/soca/obs/config/sss_smap_jpl.yaml
  parm/soca/obs/config/sss_smos.yaml
  parm/soca/obs/config/sss_smos_esa.yaml
  parm/soca/obs/config/sss_trak_fnmoc.yaml
  parm/soca/obs/config/sst_amsr2_l3u.yaml
  parm/soca/obs/config/sst_drifter.yaml
  parm/soca/obs/config/sst_gmi_l3u.yaml
  parm/soca/obs/config/sst_metopa_l3u_so025.yaml
  parm/soca/obs/config/sst_metopb_l3u_so025.yaml
  parm/soca/obs/config/sst_metopc_l3u_so025.yaml
  parm/soca/obs/config/sst_noaa18_l3u_so025.yaml
  parm/soca/obs/config/sst_ostia.yaml
  parm/soca/obs/config/sst_ship_fnmoc.yaml
  parm/soca/obs/config/sst_trak_fnmoc.yaml
  parm/soca/obs/config/sst_viirs_n20_l3u_so025.yaml
  parm/soca/obs/config/sst_viirs_npp_l3u_so025.yaml
  parm/soca/obs/config/sst_windsat_l3u.yaml
  parm/soca/obs/config/temp_bufr_dbuoyprof.yaml
  parm/soca/obs/config/temp_bufr_mbuoybprof.yaml
  parm/soca/obs/config/temp_profile_fnmoc.yaml
  parm/soca/obs/config/temp_profile_fnmoc_godas.yaml
  parm/soca/obs/config/temp_profile_wod.yaml
Labels: orion-RT-Passed, hera-RT-Passed

#240 Some updates to land_create_ensemble and land_imsproc.
  test/land/CMakeLists.txt
  test/land/create_bkg_ens.sh
  test/land/test_imsproc.sh
  ush/land/letkf_create_ens.py
Labels: orion-RT-Passed, hera-RT-Passed

#248 Add a ctest using letkfoi to assimilate GTS snow depth.
  test/land/CMakeLists.txt
  test/land/letkfoi_snowda.sh
  ush/land/genYAML_output_letkfoi.yaml
Labels: orion-RT-Passed, hera-RT-Passed

#249 Make genYAML not depend on ufsda module; allows for UFO acceptance testing to work again
  test/CMakeLists.txt
  test/genYAML_prep.sh
  test/test_generate_yaml.py
  ush/genYAML
  ush/ufoeval/run_ufo_hofx_test.sh
Labels: orion-RT-Passed, hera-RT-Passed

#244 ATM 3DVAR ctests using g-w j-jobs
  parm/atm/obs/config/amsua_n19.yaml
  parm/atm/variational/3dvar_dripcg.yaml
  test/atm/CMakeLists.txt
  test/atm/global-workflow/CMakeLists.txt
  test/atm/global-workflow/config.atmanal
  test/atm/global-workflow/config.base.emc.dyn
  test/atm/global-workflow/config.yaml
  test/atm/global-workflow/gdas_prototype.yaml
  test/atm/global-workflow/jjob_post.sh
  test/atm/global-workflow/jjob_prep.sh
  test/atm/global-workflow/jjob_run.sh
  test/atm/global-workflow/setup_workflow_exp.sh
  test/genYAML_prep.sh
  ush/genYAML
  ush/ufsda/archive.py
  ush/ufsda/misc_utils.py
  ush/ufsda/stage.py
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#252 Feature/soca remove cdate
  parm/soca/obs/config/adt_j3.yaml
  parm/soca/obs/config/icec_emc.yaml
  parm/soca/obs/config/salt_profile_fnmoc.yaml
  parm/soca/obs/config/sss_smap.yaml
  parm/soca/obs/config/sst_noaa19_l3u.yaml
  parm/soca/obs/config/sst_noaa19_l3u_so025.yaml
  scripts/exgdas_global_marine_analysis_prep.py
  test/soca/CMakeLists.txt
  test/soca/gw/config.base
  test/soca/gw/runtime_vars.sh
  test/soca/runtime_vars.sh
  test/soca/test_prep.sh
  ush/ufsda/misc_utils.py
Labels: orion-RT-Passed, hera-RT-Passed, hera-GW-RT-Passed, orion-GW-RT-Passed
