Repository NOAA-EMC/GDASApp, pull requests merged in 2023-10, with the labels that each got.

#656 Update GDASApp to spack-stack/1.5.0
  modulefiles/GDAS/hera.lua
  modulefiles/GDAS/orion.lua
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#673 Fix meanioda example now that timeWindow has been added
  utils/ioda_example/gdas_meanioda.h
  utils/test/testinput/gdas_meanioda.yaml
Labels: hera-GW-RT-Passed, orion-GW-RT-Running

#671 GHRSST and Superobing
  utils/obsproc/Ghrsst2Ioda.h
  utils/obsproc/NetCDFToIodaConverter.h
  utils/obsproc/applications/gdas_obsprovider2ioda.h
  utils/obsproc/superob.h
  utils/test/CMakeLists.txt
  utils/test/testinput/gdas_ghrsst2ioda.yaml
Labels: hera-GW-RT-Passed, orion-GW-RT-Running

#675 Add underscore (_) to IodaVar class member variable names
  utils/obsproc/Ghrsst2Ioda.h
  utils/obsproc/IcecAmsr2Ioda.h
  utils/obsproc/NetCDFToIodaConverter.h
  utils/obsproc/Rads2Ioda.h
  utils/obsproc/Smap2Ioda.h
  utils/obsproc/Smos2Ioda.h
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#690 Only use the gdas backgrounds
  scripts/exgdas_global_marine_analysis_prep.py
Labels: orion-GW-RT-Failed, hera-GW-RT-Running

#687 Add Obs. trimming function to IODA converter of icec and sss_smap
  utils/obsproc/IcecAmsr2Ioda.h
  utils/obsproc/Smap2Ioda.h
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#691 Comment out aero tests
  test/aero/CMakeLists.txt
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed
