Repository NOAA-EMC/GDASApp, pull requests merged in 2023-07, with the labels that each got.

#522 Update for new EVA convention
  ush/eva/jedi_gsi_compare_conv.yaml
  ush/eva/jedi_gsi_compare_rad.yaml
  ush/eva/jedi_gsi_compare_rad_summary.yaml
  ush/eva/marine_eva_post.py
  ush/eva/marine_gdas_plots.yaml
Labels: hera-GW-RT-Passed

#521 Replace all instances of `pygw` with `wxflow`
  .github/workflows/unittests.yaml
  .github/workflows/unittests_g-w.yaml
  scripts/exgdas_global_marine_analysis_post.py
  scripts/exgdas_global_marine_analysis_prep.py
  test/aero/genyaml_3dvar.sh
  test/atm/global-workflow/jjob_ens_final.sh
  test/atm/global-workflow/jjob_ens_init.sh
  test/atm/global-workflow/jjob_ens_run.sh
  test/atm/global-workflow/jjob_var_final.sh
  test/atm/global-workflow/jjob_var_init.sh
  test/atm/global-workflow/jjob_var_run.sh
  test/atm/global-workflow/run_jedi_exe_3denvar.sh
  test/atm/global-workflow/run_jedi_exe_3dhofx.sh
  test/atm/global-workflow/run_jedi_exe_3dvar.sh
  test/atm/global-workflow/run_jedi_exe_letkf.sh
  test/check_valid_yaml.py
  test/soca/CMakeLists.txt
  test/soca/gw/CMakeLists.txt
  ush/ioda/gen_bufr2ioda_yaml.py
  ush/run_jedi_exe.py
  ush/soca/run_jjobs.py
  ush/socaincr2mom6.py
  ush/ufsda/archive.py
  ush/ufsda/genYAML.py
  ush/ufsda/stage.py
  ush/ufsda/yamltools.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#533 Add ctest to convert bufr to ioda for adpsfc snow.
  test/CMakeLists.txt
  test/land/CMakeLists.txt
  test/testinput/bufr_adpsfc_snow.yaml
Labels: orion-GW-RT-Failed, hera-GW-RT-Passed

#537 Move fieldmetadata to inside version control rather than glopara fix
  parm/aero/hofx/hofx_nomodel.yaml
  parm/aero/variational/3dvar_gfs_aero.yaml
  parm/atm/hofx/hofx4d.yaml
  parm/atm/hofx/hofx_nomodel.yaml
  parm/atm/lgetkf/lgetkf.yaml
  parm/atm/variational/3dvar_dripcg.yaml
  parm/io/fv3jedi_fieldmetadata_history.yaml
  parm/io/fv3jedi_fieldmetadata_restart.yaml
  parm/land/hofx/hofx_nomodel.yaml
  parm/land/letkfoi/letkfoi.yaml
  test/land/letkfoi_snowda.sh
  ush/land/genYAML_output_letkfoi.yaml
  ush/ufsda/stage.py
  ush/ufsda/yamltools.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#524 Applications for generating mom6 increment and hybrid-weights
  CMakeLists.txt
  build.sh
  parm/soca/variational/socaincr2mom6.yaml
  scripts/exgdas_global_marine_analysis_chkpt.sh
  scripts/exgdas_global_marine_analysis_prep.py
  test/atm/global-workflow/jjob_ens_final.sh
  test/atm/global-workflow/jjob_ens_init.sh
  test/atm/global-workflow/jjob_ens_run.sh
  test/atm/global-workflow/jjob_var_final.sh
  test/atm/global-workflow/jjob_var_init.sh
  test/atm/global-workflow/jjob_var_run.sh
  test/atm/global-workflow/run_jedi_exe_3denvar.sh
  test/atm/global-workflow/run_jedi_exe_3dhofx.sh
  test/atm/global-workflow/run_jedi_exe_3dvar.sh
  test/atm/global-workflow/run_jedi_exe_letkf.sh
  test/soca/gw/CMakeLists.txt
  test/soca/gw/copy_scratch.sh
  test/soca/gw/run_gdas_apps.yaml.test
  test/soca/gw/run_jjobs.yaml.test
  test/soca/testinput/socahybridweights.yaml
  test/soca/testinput/socaincr2mom6.yaml
  ush/soca/run_jjobs.py
  utils/CMakeLists.txt
  utils/gdas_socahybridweights.cc
  utils/gdas_socahybridweights.h
  utils/gdas_socaincr2mom6.cc
  utils/gdas_socaincr2mom6.h
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#539 Filtering of the offline ensemble members, and more ...
  CMakeLists.txt
  parm/soca/berror/saber_block_ens.yaml
  parm/soca/berror/saber_blocks.yaml
  parm/soca/berror/soca_apply_steric.yaml
  parm/soca/berror/soca_bump_loc.yaml
  parm/soca/berror/soca_bump_split.yaml
  parm/soca/berror/soca_clim_ens_moments.yaml
  parm/soca/berror/soca_clim_ens_perts.yaml
  parm/soca/berror/soca_ensweights.yaml
  parm/soca/berror/soca_setlocscales.yaml
  parm/soca/obs/config/salt_profile_fnmoc.yaml
  parm/soca/obs/config/temp_profile_fnmoc.yaml
  parm/soca/variational/3dvarfgat.yaml
  parm/soca/variational/socaincr2mom6.yaml
  scripts/exgdas_global_marine_analysis_bmat.sh
  scripts/exgdas_global_marine_analysis_post.py
  scripts/exgdas_global_marine_analysis_prep.py
  test/soca/testinput/socaincr2mom6.yaml
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed
