Repository NOAA-EMC/GDASApp, pull requests merged in 2023-12, with the labels that each got.

#787 Recentering around the deterministic
  CMakeLists.txt
  parm/soca/berror/soca_ensb.yaml
  utils/soca/gdas_ens_handler.h
  utils/test/CMakeLists.txt
Labels: hera-GW-RT-Passed

#791 Remove the bump correlation configuration
  scripts/exgdas_global_marine_analysis_bmat.sh
  scripts/exgdas_global_marine_analysis_prep.py
Labels: hera-GW-RT-Passed

#799 Add the IODA converter for VIIRS AOD obs
  utils/obsproc/NetCDFToIodaConverter2D.h
  utils/obsproc/Viirsaod2Ioda.h
  utils/obsproc/applications/gdas_obsprovider2ioda.h
  utils/test/CMakeLists.txt
  utils/test/prepdata.sh
  utils/test/testdata/viirs_aod_1.cdl
  utils/test/testdata/viirs_aod_2.cdl
  utils/test/testinput/gdas_viirsaod2ioda.yaml
Labels: orion-GW-RT-Failed, hera-GW-RT-Passed

#797 Add some error handling to marine obs prep task
  scripts/exglobal_prep_ocean_obs.py
  ush/soca/prep_marine_obs.py
Labels: hera-GW-RT-Passed

#808 Code clean-up and a reference test for VIIRS AOD IODA converter
  utils/obsproc/NetCDFToIodaConverter.h
  utils/obsproc/NetCDFToIodaConverter2D.h
  utils/obsproc/Viirsaod2Ioda.h
  utils/obsproc/util.h
  utils/test/testinput/gdas_viirsaod2ioda.yaml
  utils/test/testref/viirsaod2ioda.test
Labels: hera-GW-RT-Failed

#817 Updated var yamls
  parm/atm/variational/3dvar_dripcg.yaml
  parm/soca/variational/3dvarfgat.yaml
Labels: hera-GW-RT-Failed

#786 Fix test reference mismatch
  utils/obsproc/IcecAmsr2Ioda.h
  utils/obsproc/Smap2Ioda.h
  utils/test/CMakeLists.txt
  utils/test/testref/icecamsr2ioda.test
  utils/test/testref/rads2ioda.test
  utils/test/testref/smap2ioda.test
Labels: hera-GW-RT-Failed

#821 Adding a feature Metadata/ocean-basin-flag to all ioda converters
  utils/obsproc/Ghrsst2Ioda.h
  utils/obsproc/IcecAmsr2Ioda.h
  utils/obsproc/NetCDFToIodaConverter.h
  utils/obsproc/Rads2Ioda.h
  utils/obsproc/Smap2Ioda.h
  utils/obsproc/Smos2Ioda.h
  utils/test/testinput/gdas_ghrsst2ioda.yaml
  utils/test/testinput/gdas_icecamsr2ioda.yaml
  utils/test/testinput/gdas_smap2ioda.yaml
  utils/test/testinput/gdas_smos2ioda.yaml
Labels: hera-GW-RT-Failed

#819 Copy prepped marine obs to ROTDIR
  scripts/exglobal_prep_ocean_obs.py
  test/soca/gw/CMakeLists.txt
  test/soca/gw/prepdata.sh
  test/soca/gw/setup_obsproc.sh
  utils/test/prepdata.sh
Labels: hera-GW-RT-Failed, hera-GW-RT-Running

#825 Ocean obs prep ctest now processes ssts on 20180415
  parm/soca/obsproc/obs_list_obsproc.yaml
  parm/soca/obsproc/obsproc_config_test.yaml
  scripts/exglobal_prep_ocean_obs.py
  test/soca/gw/prepdata.sh
  test/soca/gw/setup_obsproc.sh
  test/soca/testdata/20180415095000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/20180415114000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/20180415132000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
Labels: hera-GW-RT-Failed
