Repository NOAA-EMC/GDASApp, pull requests merged in 2023-05, with the labels that each got.

#456 update atm var and ens ctests to new GFS COM directory structure (#455)
  test/atm/global-workflow/config.atmanl
  test/atm/global-workflow/config.base.emc.dyn
  test/atm/global-workflow/jjob_ens_init.sh
  test/atm/global-workflow/jjob_var_init.sh
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#461 add ensemble based bump localization to gsibec hybvar yaml
  parm/atm/berror/hybvar_gsibec.yaml
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#457 Adapt the marine DA to the new COM structure
  .gitignore
  scripts/exgdas_global_marine_analysis_chkpt.sh
  scripts/exgdas_global_marine_analysis_post.py
  scripts/exgdas_global_marine_analysis_prep.py
  scripts/exgdas_global_marine_analysis_vrfy.py
  test/atm/global-workflow/run_jedi_exe_3denvar.sh
  test/atm/global-workflow/run_jedi_exe_3dhofx.sh
  test/atm/global-workflow/run_jedi_exe_3dvar.sh
  test/atm/global-workflow/run_jedi_exe_letkf.sh
  test/soca/CMakeLists.txt
  test/soca/gw/CMakeLists.txt
  test/soca/gw/prep.sh
  test/soca/gw/run_jjobs.yaml.test
  test/soca/gw/static.sh
  test/soca/runtime_vars.sh
  test/soca/test_bmat.sh
  test/soca/test_bmat_vrfy.sh
  test/soca/test_prep.sh
  test/soca/test_run.sh
  test/soca/test_utils.sh
  ush/soca/run_jjobs.py
  ush/ufsda/stage.py
Labels: hera-GW-RT-Passed, orion-GW-RT-Running

#470 Script to clone, build workflow and generate experiment for prototypes
  modulefiles/GDAS/hera.lua
  modulefiles/GDAS/orion.lua
  parm/atm/berror/hybvar_bump.yaml
  parm/atm/berror/hybvar_gsibec.yaml
  parm/atm/lgetkf/lgetkf.yaml
  prototypes/configs/cp0.sh
  prototypes/gen_prototype.sh
  test/CMakeLists.txt
  test/atm/global-workflow/config.base.emc.dyn
  test/atm/global-workflow/config.yaml
  test/atm/global-workflow/jjob_ens_final.sh
  test/atm/global-workflow/jjob_ens_init.sh
  test/atm/global-workflow/jjob_ens_run.sh
  test/atm/global-workflow/jjob_var_init.sh
  test/atm/global-workflow/setup_workflow_exp.sh
  test/setup_workflow_exp.sh
  test/soca/gw/run_jjobs.yaml.test
  ush/run_jedi_exe.py
  ush/soca/run_jjobs.py
  ush/ufsda/stage.py
Labels: hera-GW-RT-Passed, orion-GW-RT-Running

#484 Don't look yet ...
  parm/soca/berror/saber_blocks.yaml
  test/soca/gw/run_jjobs.yaml.test
  ush/soca/run_jjobs.py
Labels: hera-GW-RT-Passed

#492 Addition of a climatological ensemble B to the soca B-matrix
  parm/soca/berror/saber_blocks.yaml
  parm/soca/berror/soca_bump_loc.yaml
  parm/soca/berror/soca_setcorscales.yaml
  parm/soca/variational/3dvarfgat.yaml
  scripts/exgdas_global_marine_analysis_bmat.sh
  scripts/exgdas_global_marine_analysis_prep.py
  test/setup_workflow_exp.sh
  test/soca/gw/CMakeLists.txt
  test/soca/gw/prep.sh
Labels: hera-GW-RT-Passed
