Repository NOAA-EMC/GDASApp, pull requests merged in 2023-01, with the labels that each got.

#258 ATM letkf ctests using g-w j-jobs
  parm/atm/lgetkf/lgetkf.yaml
  parm/atm/obs/config/lgetkf_amsua_n19.yaml
  parm/atm/obs/config/lgetkf_sondes.yaml
  parm/atm/obs/config/sfcship.yaml
  parm/atm/obs/config/sondes.yaml
  test/atm/global-workflow/CMakeLists.txt
  test/atm/global-workflow/config.yaml
  test/atm/global-workflow/jjob_ens_post.sh
  test/atm/global-workflow/jjob_ens_prep.sh
  test/atm/global-workflow/jjob_ens_run.sh
  test/atm/global-workflow/jjob_var_post.sh
  test/atm/global-workflow/jjob_var_prep.sh
  test/atm/global-workflow/jjob_var_run.sh
  test/atm/global-workflow/setup_workflow_exp.sh
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#262 adding more error handling to soca run scripts, other refinements
  scripts/exgdas_global_marine_analysis_run.sh
  test/soca/gw/bkg2comrot.sh
  test/soca/gw/jjob_prep.sh
Labels: orion-RT-Passed, hera-RT-Passed

#259 Upgrade a 'create_ens' script to remove water and glacier locations.
  CMakeLists.txt
  ush/land/letkf_create_ens.py
Labels: hera-RT-Passed, orion-RT-Running

#264 precleaning output before ctests
  test/CMakeLists.txt
  test/soca/CMakeLists.txt
  test/soca/test_bufr2ioda.sh
  test/testinput/bufr_tesacprof.yaml
  test/testinput/bufr_trkobprof.yaml
Labels: orion-RT-Passed, hera-RT-Passed

#265 Minor updates related soca running in the g-w
  scripts/exgdas_global_marine_analysis_prep.py
  scripts/exgdas_global_marine_analysis_run.sh
  test/soca/test_run.sh
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#268 remove output before db test, tweaks to bufr2ioda test
  test/soca/create_obsdb.py
  test/soca/test_bufr2ioda.sh
Labels: orion-RT-Passed, hera-RT-Passed

#267 Minor cleanup of bump's implementation
  parm/soca/berror/soca_bump2d.yaml
  parm/soca/berror/soca_bump_split.yaml
  scripts/exgdas_global_marine_analysis_prep.py
  scripts/exgdas_global_marine_analysis_run.sh
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#272 add soca bmat script plus ctest
  scripts/exgdas_global_marine_analysis_bmat.sh
  test/soca/CMakeLists.txt
  test/soca/test_bmat.sh
Labels: orion-RT-Passed, hera-RT-Passed

#274 B-matrix diagnostics
  parm/soca/berror/saber_blocks.yaml
  scripts/exgdas_global_marine_analysis_bmat_vrfy.sh
  test/soca/CMakeLists.txt
  test/soca/test_bmat_vrfy.sh
  ush/ufsda/dirac_yaml.py
Labels: orion-RT-Passed, hera-RT-Passed

#270 More user defined experiment parameters for the marine DA
  parm/soca/berror/saber_block_ens.yaml
  parm/soca/berror/soca_bump2d.yaml
  parm/soca/berror/soca_bump_split.yaml
  parm/soca/obs/config/obs_list.yaml
  parm/soca/variational/3dvarfgat.yaml
  scripts/exgdas_global_marine_analysis_prep.py
  test/soca/gw/CMakeLists.txt
  test/soca/gw/config.yaml
  test/soca/gw/jjob_prep.sh
  test/soca/gw/jjob_run.sh
  test/soca/gw/runtime_vars.sh
  test/soca/gw/setup_workflow_exp.sh
  test/soca/runtime_vars.sh
  ush/soca/examples/run_jjobs_container.yaml
  ush/soca/examples/run_jjobs_hera.yaml
  ush/soca/examples/run_jjobs_hera_025.yaml
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#281 Ignoring the ioda variable name convention changes for the time being.
  CMakeLists.txt
Labels: hera-GW-RT, orion-GW-RT

#285 Cleanup soca j-job ctests
  test/soca/gw/CMakeLists.txt
  test/soca/gw/bkg2comrot.sh
  test/soca/gw/config.base
  test/soca/gw/config.yaml
  test/soca/gw/jjob_prep.sh
  test/soca/gw/jjob_run.sh
  test/soca/gw/run_jjobs.yaml.test
  test/soca/gw/runtime_vars.sh
  test/soca/gw/setup_workflow_exp.sh
  ush/soca/run_jjobs.py
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#278 Enable run_jedi_exe.py to run 3dvar
  parm/atm/berror/staticb_gsibec.yaml
  scripts/exgdas_global_marine_analysis_prep.py
  ush/examples/run_jedi_exe/3dvar_hera.yaml
  ush/examples/run_jedi_exe/3dvar_orion.yaml
  ush/genYAML
  ush/run_jedi_exe.py
  ush/ufsda/__init__.py
  ush/ufsda/genYAML.py
  ush/ufsda/misc_utils.py
  ush/ufsda/stage.py
  ush/ufsda/yamltools.py
Labels: orion-RT-Passed, hera-RT-Passed, hera-GW-RT-Failed, orion-GW-RT-Failed

#287 changing acount for jjob soca test
  test/soca/gw/run_jjobs.yaml.test
Labels: orion-RT-Running, hera-RT-Running

#282 added receipt time to soca bufr2ioda yamls
  test/testinput/bufr_sfcships.yaml
  test/testinput/bufr_sfcshipsu.yaml
  test/testinput/bufr_tesacprof.yaml
  test/testinput/bufr_trkobprof.yaml
  test/testinput/salt_bufr_dbuoyprof.yaml
  test/testinput/salt_bufr_mbuoybprof.yaml
  test/testinput/temp_bufr_dbuoyprof.yaml
  test/testinput/temp_bufr_mbuoybprof.yaml
Labels: orion-RT-Passed, hera-RT-Passed

#296 Feature/add soca bmat jjob
  test/soca/gw/CMakeLists.txt
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#297 Use new convention for AOD
  parm/aero/obs/config/viirs_n20_aod.yaml
  parm/aero/obs/config/viirs_npp_aod.yaml
Labels: AeroDA

#299 remove non-run items from soca run
  scripts/exgdas_global_marine_analysis_run.sh
Labels: orion-RT-Passed, hera-RT-Passed

#286 Plot marine DA stuff
  scripts/exgdas_global_marine_analysis_prep.py
  scripts/exgdas_global_marine_analysis_run.sh
  scripts/exgdas_global_marine_analysis_vrfy.py
  test/soca/gw/CMakeLists.txt
  test/soca/test_run.sh
  ush/soca/run_jjobs.py
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed
