Repository NOAA-EMC/GDASApp, pull requests merged in 2023-11, with the labels that each got.

#700 Add functionality to locally change the weights used for the hybrid B
  parm/soca/berror/soca_ensb.yaml
  parm/soca/berror/soca_ensweights.yaml
  test/soca/testinput/socahybridweights.yaml
  utils/soca/gdas_ens_handler.h
  utils/soca/gdas_socahybridweights.h
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#703 Feature/nick e sfcshp prepbufr
  parm/ioda/bufr2ioda/bufr2ioda_sfcshp_prepbufr.json
  ush/ioda/bufr2ioda/bufr2ioda_sfcshp_prepbufr.py
  ush/ioda/bufr2ioda/run_bufr2ioda.py
Labels: documentation

#707 Fix the failing test_gdasapp_land_letkfoi_snowda
  test/land/letkfoi_land.yaml
Labels: hera-GW-RT-Failed

#717 GHRSST bug fix ... an more
  utils/obsproc/Ghrsst2Ioda.h
  utils/obsproc/NetCDFToIodaConverter.h
  utils/obsproc/superob.h
  utils/test/CMakeLists.txt
  utils/test/testinput/gdas_ghrsst2ioda.yaml
  utils/test/testref/ghrsst2ioda.test
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#738 "Fix" for the increment handler application
  test/soca/testinput/incr_handler.yaml
  utils/soca/gdas_incr_handler.h
Labels: hera-GW-RT-Failed, orion-GW-RT-Passed

#732 Adding ocean basin in the Metadata
  utils/obsproc/Ghrsst2Ioda.h
  utils/obsproc/IcecAmsr2Ioda.h
  utils/obsproc/NetCDFToIodaConverter.h
  utils/obsproc/Rads2Ioda.h
  utils/obsproc/Smap2Ioda.h
  utils/obsproc/Smos2Ioda.h
  utils/obsproc/util.h
  utils/test/testinput/gdas_rads2ioda.yaml
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#744 Linear time interpolation for FGAT
  parm/soca/obs/config/adt_3a_egm2008.yaml
  parm/soca/obs/config/adt_3b_egm2008.yaml
  parm/soca/obs/config/adt_6a_egm2008.yaml
  parm/soca/obs/config/adt_all.yaml
  parm/soca/obs/config/adt_c2_egm2008.yaml
  parm/soca/obs/config/adt_coperl4.yaml
  parm/soca/obs/config/adt_j2.yaml
  parm/soca/obs/config/adt_j2_egm2008.yaml
  parm/soca/obs/config/adt_j3.yaml
  parm/soca/obs/config/adt_j3_egm2008.yaml
  parm/soca/obs/config/adt_sa_egm2008.yaml
  parm/soca/obs/config/icec_amsr2_north.yaml
  parm/soca/obs/config/icec_amsr2_south.yaml
  parm/soca/obs/config/icec_emc.yaml
  parm/soca/obs/config/icec_nsidc_nh.yaml
  parm/soca/obs/config/icec_nsidc_sh.yaml
  parm/soca/obs/config/icec_ssmis_f17_north.yaml
  parm/soca/obs/config/icec_ssmis_f17_south.yaml
  parm/soca/obs/config/icec_ssmis_f18_north.yaml
  parm/soca/obs/config/icec_ssmis_f18_south.yaml
  parm/soca/obs/config/icefb_gdr.yaml
  parm/soca/obs/config/sss_smap.yaml
  parm/soca/obs/config/sss_smap_jpl.yaml
  parm/soca/obs/config/sss_smos.yaml
  parm/soca/obs/config/sss_smos_esa.yaml
  parm/soca/obs/config/sst_gmi_l3u.yaml
  parm/soca/obs/config/sst_metopa_l3u_so025.yaml
  parm/soca/obs/config/sst_metopb_l3u_so025.yaml
  parm/soca/obs/config/sst_metopc_l3u_so025.yaml
  parm/soca/obs/config/sst_noaa18_l3u_so025.yaml
  parm/soca/obs/config/sst_noaa19_l3u.yaml
  parm/soca/obs/config/sst_noaa19_l3u_so025.yaml
  parm/soca/obs/config/sst_viirs_n20_l3u_so025.yaml
  parm/soca/obs/config/sst_viirs_npp_l3u_so025.yaml
  parm/soca/obs/config/sst_windsat_l3u.yaml
Labels: hera-GW-RT-Failed, orion-GW-RT-Passed

#747 Switch to std::vector in Rads2Ioda.h
  utils/obsproc/Rads2Ioda.h
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#756 Fix a bug for dateTime in IcecAmsr2Ioda.h
  utils/obsproc/IcecAmsr2Ioda.h
Labels: orion-GW-RT-Failed, hera-GW-RT-Passed

#771 Add an option to point to the "enkfgdas" backgrounds instead of the pre-generated 30 member ensemble
  parm/soca/berror/saber_blocks.yaml
  parm/soca/berror/soca_ensb.yaml
  scripts/exgdas_global_marine_analysis_bmat_vrfy.sh
  scripts/exgdas_global_marine_analysis_prep.py
  test/soca/gw/CMakeLists.txt
  test/soca/gw/prep.sh
  test/soca/gw/run_jjobs.yaml.test
  ush/soca/run_jjobs.py
Labels: hera-GW-RT-Passed

#719 Add IODA conversions to marine obs prep task ex-script
  parm/soca/obsproc/obs_list_obsproc.yaml
  parm/soca/obsproc/obsproc_config.yaml
  parm/soca/obsproc/obsproc_config_test.yaml
  scripts/exglobal_prep_ocean_obs.py
  test/soca/gw/CMakeLists.txt
  test/soca/gw/run_jjobs.yaml.test
  test/soca/gw/setup_obsproc.sh
  ush/soca/prep_marine_obs.py
  ush/soca/run_jjobs.py
  utils/test/prepdata.sh
Labels: hera-GW-RT-Failed
