Repository NOAA-EMC/GDASApp, pull requests merged in 2023-08, with the labels that each got.

#538 Refactoring of vrfy - transferred bulk of plotting to sub-script
  scripts/exgdas_global_marine_analysis_vrfy.py
  ush/soca/diag_statistics.py
  ush/soca/soca_vrfy.py
Labels: orion-GW-RT, hera-GW-RT-Failed

#550 Actually switch to CRTM 2.4 now
  modulefiles/GDAS/hera.lua
  modulefiles/GDAS/orion.lua
  test/atm/global-workflow/config.atmanl
  ush/ufoeval/run_ufo_hofx_test.sh
  ush/ufsda/stage.py
Labels: hera-GW-RT-Failed

#551 removed duplicate variable specification
  scripts/exgdas_global_marine_analysis_vrfy.py
  ush/soca/soca_vrfy.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#553 Added example utility using OOPS and IODA
  utils/CMakeLists.txt
  utils/ioda_example/CMakeLists.txt
  utils/ioda_example/gdas_meanioda.cc
  utils/ioda_example/gdas_meanioda.h
  utils/soca/CMakeLists.txt
  utils/soca/gdas_incr_handler.cc
  utils/soca/gdas_incr_handler.h
  utils/soca/gdas_postprocincr.h
  utils/soca/gdas_socahybridweights.cc
  utils/soca/gdas_socahybridweights.h
  utils/test/CMakeLists.txt
  utils/test/testinput/gdas_meanioda.yaml
Labels: hera-GW-RT-Failed

#555 Add in a C++ linter
  .github/workflows/norms.yaml
  utils/CPPLINT.cfg
  utils/ioda_example/gdas_meanioda.h
  utils/soca/gdas_incr_handler.h
  utils/soca/gdas_postprocincr.h
  utils/soca/gdas_socahybridweights.h
  utils/test/CMakeLists.txt
  utils/test/cpplint.py
Labels: hera-GW-RT-Failed

#574 Fix test_gdasapp_convert_bufr_adpsfc_snow ctest
  test/land/test_bufr2ioda.sh
Labels: hera-RT-Passed, hera-GW-RT-Passed

#578 adding titles to vrfy plots
  CMakeLists.txt
  scripts/exgdas_global_marine_analysis_vrfy.py
  ush/soca/soca_vrfy.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#588 Add in basic C48 aerosol analysis tests that use global-workflow
  parm/aero/variational/3dvar_gfs_aero.yaml
  test/aero/CMakeLists.txt
  test/aero/global-workflow/CMakeLists.txt
  test/aero/global-workflow/config.aeroanl
  test/aero/global-workflow/config.yaml
  test/aero/global-workflow/gdas_prototype.yaml
  test/aero/global-workflow/jjob_var_final.sh
  test/aero/global-workflow/jjob_var_init.sh
  test/aero/global-workflow/jjob_var_run.sh
  test/aero/global-workflow/setup_workflow_exp.sh
Labels: AeroDA

#591 replace params with local configration in soca utility
  utils/soca/gdas_postprocincr.h
Labels: hera-GW-RT-Failed, orion-GW-RT-Passed
