Repository NOAA-EMC/GDASApp, pull requests merged in 2023-02, with the labels that each got.

#307 removed pythonpath construction from script
  scripts/exgdas_global_marine_analysis_prep.py
Labels: orion-RT-Passed, hera-RT-Passed

#314 New B-matrix
  parm/soca/berror/saber_blocks.yaml
  parm/soca/variational/3dvarfgat.yaml
  scripts/exgdas_global_marine_analysis_bmat.sh
  scripts/exgdas_global_marine_analysis_bmat_vrfy.sh
  scripts/exgdas_global_marine_analysis_prep.py
  scripts/exgdas_global_marine_analysis_run.sh
  scripts/exgdas_global_marine_analysis_vrfy.py
  test/soca/static.sh
  test/soca/test_prep.sh
  ush/soca/run_jjobs.py
  ush/ufsda/dirac_yaml.py
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#328 Feature/sprint ioda converters
  CMakeLists.txt
  parm/aero/obs/config/viirs_n20_aod.yaml
  parm/aero/obs/config/viirs_npp_aod.yaml
  parm/atm/obs/config/omi_aura.yaml
  parm/atm/obs/config/ompsnp_npp.yaml
  parm/atm/obs/config/ompstc8_npp.yaml
  parm/atm/obs/config/satwind.yaml
  parm/atm/obs/config/sfc.yaml
  parm/atm/obs/config/sfcship.yaml
  parm/atm/obs/config/sondes.yaml
  parm/atm/obs/testing/aircraft.yaml
  parm/atm/obs/testing/amsua_n19.yaml
  parm/atm/obs/testing/satwind.yaml
  parm/atm/obs/testing/sfc.yaml
  parm/atm/obs/testing/sfcship.yaml
  parm/atm/obs/testing/sondes.yaml
  parm/atm/obs/testing/sondes_ps.yaml
  parm/atm/obs/testing/ssmis_f17.yaml
  parm/atm/obs/testing/ssmis_f18.yaml
  parm/soca/berror/saber_blocks.yaml
  parm/soca/berror/soca_bump2d.yaml
  parm/soca/berror/soca_bump_split.yaml
  parm/soca/obs/config/adt_j3.yaml
  parm/soca/obs/config/icec_emc.yaml
  parm/soca/obs/config/salt_profile_fnmoc.yaml
  parm/soca/obs/config/sss_smap.yaml
  parm/soca/obs/config/sst_noaa19_l3u.yaml
  test/soca/CMakeLists.txt
  test/soca/create_obsdb.py
  test/soca/static.sh
  test/soca/testdata/adt.nc.cdl
  test/soca/testdata/icec.nc.cdl
  test/soca/testdata/prof.nc.cdl
  test/soca/testdata/sss.nc.cdl
  test/soca/testdata/sst.nc.cdl
  ush/eva/jedi_gsi_compare_conv.yaml
  ush/ufoeval/run_ufo_hofx_test.sh
  ush/ufsda/stage.py
Labels: orion-GW-RT-Failed

#339 Update the yamls for ctest land_letkfoi_snowda
  parm/land/obs/config/adpsfc_snow.yaml
  parm/land/obs/config/ghcn_snow.yaml
  parm/land/obs/config/ims_snow.yaml
  ush/land/genYAML_output_letkfoi.yaml
Labels: orion-RT-Passed, hera-RT-Passed

#335 Remove redundant marine ctests
  parm/soca/obs/obs_list.yaml
  test/soca/CMakeLists.txt
  test/soca/gw/CMakeLists.txt
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#338 Feature/obs tests
  ush/eva/jedi_gsi_compare_rad.yaml
  ush/eva/jedi_gsi_compare_rad_summary.yaml
  ush/ufoeval/run_ufo_hofx_test.sh
  ush/ufoeval/test_yamls.sh
Labels: orion-RT-Failed, hera-RT-Failed

#324 A few updates to adapt soca to the G-W UFS output
  ci/run_gw_ci.sh
  parm/soca/variational/3dvarfgat.yaml
  scripts/exgdas_global_marine_analysis_prep.py
  scripts/exgdas_global_marine_analysis_run.sh
  test/CMakeLists.txt
  test/soca/CMakeLists.txt
  test/soca/gw/CMakeLists.txt
  test/soca/test_prep.sh
  ush/soca/run_jjobs.py
  ush/socaincr2mom6.py
Labels: orion-GW-RT-Failed, hera-GW-RT-Passed

#345 Add safeguards against timing problem in run_jedi_exe ctests
  test/atm/run_jedi_exe_3dhofx.sh
  test/atm/run_jedi_exe_3dvar.sh
  test/atm/run_jedi_exe_letkf.sh
Labels: hera-GW-RT-Running, orion-GW-RT-Running

#361 Make use of BUMP (again) in soca B
  parm/atm/obs/config/amsua_n19.yaml
  parm/soca/berror/saber_blocks.yaml
  parm/soca/variational/3dvarfgat.yaml
  scripts/exgdas_global_marine_analysis_bmat_vrfy.sh
  ush/ufsda/dirac_yaml.py
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#365 Add eva plotting to soca vrfy task
  scripts/exgdas_global_marine_analysis_vrfy.py
  ush/eva/gen_eva_obs_yaml.py
Labels: hera-GW-RT-Passed, orion-GW-RT-Running

#367 A few changes to get aerosol cycling working again
  parm/aero/berror/staticb_bump.yaml
  parm/aero/berror/staticb_bump_aero.yaml
  parm/aero/obs/config/viirs_npp_aod.yaml
  parm/aero/variational/3dvar_gfs_aero.yaml
Labels: AeroDA

#364 Modify genYAML.py to create Yaml file for the snow DA
  parm/land/letkfoi/letkfoi.yaml
  test/CMakeLists.txt
  test/genYAML_prep_land.sh
  ush/ufsda/genYAML.py
Labels: orion-RT-Passed, hera-RT-Passed
