Repository NOAA-EMC/GDASApp, pull requests merged in 2024-04, with the labels that each got.

#1018 Commenting out more of the marine bufr 2 ioda stuff
  scripts/exglobal_prep_ocean_obs.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1034 Run g-w linker script before ctest for prepoceanobs task
  test/soca/gw/setup_obsprep.sh
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1039 Fix test output for fv3jedi_fv3inc.h
  utils/fv3jedi/fv3jedi_fv3inc.h
Labels: orion-GW-RT-Failed, hera-GW-RT-Running

#1027 Fix bug for datetime in GHRSST Ioda Converter
  utils/obsproc/Ghrsst2Ioda.h
  utils/test/testref/ghrsst2ioda.test
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1040 Save basic stats in csv at each cycle
  parm/soca/obs/obs_stats.yaml.j2
  scripts/exgdas_global_marine_analysis_post.py
  ush/soca/gdassoca_obsstats.py
  utils/soca/CMakeLists.txt
  utils/soca/gdassoca_obsstats.cc
  utils/soca/gdassoca_obsstats.h
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1052 Get test data from a staged location on supported HPC Part Deux
  modulefiles/GDAS/hera.intel.lua
  modulefiles/GDAS/hercules.intel.lua
  modulefiles/GDAS/orion.intel.lua
  test/CMakeLists.txt
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1045 Get SOCA vrfy job working on Hera again
  test/soca/gw/CMakeLists.txt
  ush/soca/run_jjobs.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1056 Removing ctests of an obsolete bufr_converter in SOCA
  test/soca/CMakeLists.txt
  test/soca/test_bufr2ioda.sh
  test/testinput/bufr_sfcships.yaml
  test/testinput/bufr_sfcshipsu.yaml
  test/testinput/bufr_tesacprof.yaml
  test/testinput/bufr_trkobprof.yaml
  test/testinput/salt_bufr_dbuoyprof.yaml
  test/testinput/salt_bufr_mbuoybprof.yaml
  test/testinput/temp_bufr_dbuoyprof.yaml
  test/testinput/temp_bufr_mbuoybprof.yaml
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1050 New ocean/ice B diag
  parm/soca/berror/saber_blocks.yaml
  parm/soca/berror/soca_diagb.yaml.j2
  parm/soca/berror/soca_hybrid_bmat.yaml
  parm/soca/berror/soca_parameters_diffusion_vt.yaml
  parm/soca/berror/soca_static_bmat.yaml
  parm/soca/berror/soca_vtscales.yaml.j2
  parm/soca/fields_metadata.yaml
  parm/soca/obs/config/adt_rads_all.yaml
  parm/soca/obs/config/sst_abi_g16_l3c.yaml
  parm/soca/obs/config/sst_abi_g17_l3c.yaml
  parm/soca/obs/config/sst_ahi_h08_l3c.yaml
  parm/soca/obs/config/sst_avhrr_ma_l3u.yaml
  parm/soca/obs/config/sst_avhrr_mb_l3u.yaml
  parm/soca/obs/config/sst_avhrr_mc_l3u.yaml
  parm/soca/obs/config/sst_viirs_n20_l3u.yaml
  parm/soca/obs/config/sst_viirs_npp_l3u.yaml
  parm/soca/obsprep/obsprep_config.yaml
  scripts/exgdas_global_marine_analysis_bmat.sh
  scripts/exgdas_global_marine_analysis_post.py
  scripts/exgdas_global_marine_analysis_prep.py
  scripts/exgdas_global_marine_analysis_run.sh
  test/soca/gw/static.sh
  utils/soca/CMakeLists.txt
  utils/soca/gdas_soca_diagb.cc
  utils/soca/gdas_soca_diagb.h
  utils/test/testref/ghrsst2ioda.test
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1049 Refactoring prepocnobs task
  scripts/exglobal_prep_ocean_obs.py
  ush/ioda/bufr2ioda/marine/bufr2ioda_insitu_profile_argo.py
  ush/soca/prep_marine_obs.py
  ush/soca/prep_ocean_obs.py
  ush/soca/prep_ocean_obs_utils.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1067 Add basin flags to the ocean obs
  parm/soca/berror/soca_diagb.yaml.j2
  parm/soca/obsprep/obsprep_config.yaml
  utils/obsproc/NetCDFToIodaConverter.h
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1069 More marine DA bufixes
  test/soca/gw/run_jjobs.yaml.test
  ush/soca/prep_ocean_obs.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1070 No mpi for the ascii stats
  utils/soca/gdassoca_obsstats.h
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#1072 Addition of a switch for the cycling type
  scripts/exgdas_global_marine_analysis_post.py
  scripts/exgdas_global_marine_analysis_prep.py
Labels: orion-GW-RT-Passed, hera-GW-RT-Running

#1077 Using ioda util to convert the datetime in AMSR2 converter
  utils/obsproc/IcecAmsr2Ioda.h
Labels: hera-GW-RT-Passed, orion-GW-RT-Running

#1084 Use the gdas bkg for the static B
  parm/soca/berror/soca_diagb.yaml.j2
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed
