Repository NOAA-EMC/GDASApp, pull requests merged in 2024-03, with the labels that each got.

#946 Move bkg renamer to function
  scripts/exgdas_global_marine_analysis_prep.py
  ush/soca/bkg_utils.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Passed

#945 Fix warning for 'missing return' in Rad2Ioda.h
  utils/obsproc/Rads2Ioda.h
  utils/obsproc/util.h
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#948 fixed typos in bkg err yaml
  parm/soca/berror/saber_blocks.yaml
Labels: hera-GW-RT-Failed, orion-GW-RT-Passed

#961 Switch to FileHandler
  ush/socaincr2mom6.py
  ush/ufsda/stage.py
Labels: orion-GW-RT-Failed, hera-GW-RT-Running

#953 Fix averaging datetime on geostationary sst's
  utils/obsproc/Ghrsst2Ioda.h
  utils/test/testref/ghrsst2ioda.test
Labels: hera-GW-RT-Failed, orion-GW-RT-Passed

#968 Adds recentering task script and methods, with ctests
  parm/soca/berror/soca_ensrecenter.yaml
  parm/soca/obsprep/obsprep_config.yaml
  scripts/exgdas_global_marine_analysis_ecen.py
  test/soca/gw/CMakeLists.txt
  test/soca/gw/run_jjobs.yaml.test
  ush/soca/bkg_utils.py
  ush/soca/marine_recenter.py
  ush/ufsda/yamltools.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#827 Add updates for ozone and end-to-end results
  parm/atm/obs/config/omi_aura.yaml.j2
  parm/atm/obs/config/ompsnp_npp.yaml.j2
  parm/atm/obs/config/ompstc_npp.yaml.j2
  parm/atm/obs/lists/gdas_prototype_3d.yaml.j2
  parm/atm/obs/testing/omi_aura.yaml
  parm/atm/obs/testing/omi_aura_noqc.yaml
  parm/atm/obs/testing/ompsnp_npp.yaml
  parm/atm/obs/testing/ompsnp_npp_noqc.yaml
  parm/atm/obs/testing/ompstc_npp.yaml
  parm/atm/obs/testing/ompstc_npp_noqc.yaml
  parm/ioda/bufr2ioda/bufr2ioda_ozone_omi.json
  parm/ioda/bufr2ioda/bufr2ioda_ozone_ompsnp.json
  parm/ioda/bufr2ioda/bufr2ioda_ozone_ompstc.json
  ush/ioda/bufr2ioda/bufr2ioda_ozone_omi.py
  ush/ioda/bufr2ioda/bufr2ioda_ozone_ompsnp.py
  ush/ioda/bufr2ioda/bufr2ioda_ozone_ompstc.py
Labels: gdas validation

#989 Fix to marine DA prep
  scripts/exgdas_global_marine_analysis_prep.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#981 restore test_gdasapp_atm_jjob functionality
  test/atm/global-workflow/config.atmanl
  test/atm/global-workflow/config.atmensanl
  test/atm/global-workflow/config.yaml
Labels: orion-RT-Passed, orion-GW-RT-Passed

#928 Change $(foo) to {{ foo }} in YAMLs
  parm/atm/berror/staticb_identity.yaml.j2
  test/CMakeLists.txt
  test/convert_ewok_yaml.sh
  test/testinput/amsua_n19_ewok.yaml
  test/testreference/amsua_n19_gdas.yaml
  ush/modify_yaml_syntax.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Passed

#766 [End- to End Test code sprint] Add SEVIRI METEOSAT-8 and METEOSAT-11 to end-to-end testing
  parm/atm/obs/config/seviri_m08.yaml.j2
  parm/atm/obs/config/seviri_m11.yaml.j2
  parm/atm/obs/lists/gdas_prototype_3d.yaml.j2
  parm/ioda/bufr2ioda/bufr2ioda_sevcsr.json
  ush/ioda/bufr2ioda/bufr2ioda_sevcsr.py
Labels: gdas validation

#1001 Remove sst's from obs proc
  parm/soca/obs/obs_list.yaml
Labels: orion-GW-RT-Failed

#914 Add BUFR2IODA python API converter to prepoceanobs task
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_argo.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_bathy.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_dbuoy.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_dbuoyb.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_glider.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_marinemammals.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_mbuoy.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_mbuoyb.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_tesac.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_xbtctd.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_altkob.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_ships.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_shipsu.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_trkob.json
  parm/soca/obs/config/dev/insitu_profile_argo.yaml
  parm/soca/obs/config/dev/insitu_profile_bathy.yaml
  parm/soca/obs/config/dev/insitu_profile_dbuoy.yaml
  parm/soca/obs/config/dev/insitu_profile_dbuoyb.yaml
  parm/soca/obs/config/dev/insitu_profile_glider.yaml
  parm/soca/obs/config/dev/insitu_profile_marinemammal.yaml
  parm/soca/obs/config/dev/insitu_profile_mbuoy.yaml
  parm/soca/obs/config/dev/insitu_profile_mbuoyb.yaml
  parm/soca/obs/config/dev/insitu_profile_tesac.yaml
  parm/soca/obs/config/dev/insitu_profile_tesac_salinity.yaml
  parm/soca/obs/config/dev/insitu_profile_xbtctd.yaml
  parm/soca/obs/config/dev/insitu_surface_altkob.yaml
  parm/soca/obs/config/dev/insitu_surface_trkob.yaml
  parm/soca/obs/config/dev/insitu_surface_trkob_salinity.yaml
  parm/soca/obs/config/old/bufr/bufr_sfcships.yaml
  parm/soca/obs/config/old/bufr/bufr_sfcshipsu.yaml
  parm/soca/obs/obs_list.yaml
  parm/soca/obsprep/obsprep_config.yaml
  scripts/exglobal_prep_ocean_obs.py
  test/soca/gw/CMakeLists.txt
  test/soca/gw/run_jjobs.yaml.test
  test/soca/gw/setup_obsprep.sh
  ush/ioda/bufr2ioda/bufr2ioda_insitu_marinemammals_profiles.py
  ush/ioda/bufr2ioda/bufr2ioda_insitu_profile_bathy.py
  ush/ioda/bufr2ioda/bufr2ioda_insitu_profile_tesac.py
  ush/ioda/bufr2ioda/bufr2ioda_insitu_profiles_argo.py
  ush/ioda/bufr2ioda/bufr2ioda_insitu_profiles_glider.py
  ush/ioda/bufr2ioda/bufr2ioda_insitu_profiles_tesac.py
  ush/ioda/bufr2ioda/bufr2ioda_insitu_profiles_xbtctd.py
  ush/ioda/bufr2ioda/bufr2ioda_insitu_surface_altkob.py
  ush/ioda/bufr2ioda/bufr2ioda_insitu_surface_trkob.py
  ush/ioda/bufr2ioda/gen_bufr2ioda_json.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Passed

#1003 restore ATM local ensemble ctest functionality
  test/atm/global-workflow/config.yaml
Labels: orion-GW-RT-Failed

#1007 Moved the marine converters to a "safe" place
  ush/ioda/bufr2ioda/marine/bkp/bufr2ioda_altkob_surface.py
  ush/ioda/bufr2ioda/marine/bkp/bufr2ioda_bathythermal_profiles.py
  ush/ioda/bufr2ioda/marine/bkp/bufr2ioda_subpfl_argo_profiles.py
  ush/ioda/bufr2ioda/marine/bkp/bufr2ioda_subpfl_glider_profiles.py
  ush/ioda/bufr2ioda/marine/bkp/bufr2ioda_tesac_mammals_profiles.py
  ush/ioda/bufr2ioda/marine/bkp/bufr2ioda_tesac_profiles.py
  ush/ioda/bufr2ioda/marine/bkp/bufr2ioda_trackob_surface.py
  ush/ioda/bufr2ioda/marine/bkp/bufr2ioda_xbtctd_profiles.py
  ush/ioda/bufr2ioda/marine/bufr2ioda_insitu_marinemammals_profiles.py
  ush/ioda/bufr2ioda/marine/bufr2ioda_insitu_profile_bathy.py
  ush/ioda/bufr2ioda/marine/bufr2ioda_insitu_profile_tesac.py
  ush/ioda/bufr2ioda/marine/bufr2ioda_insitu_profiles_argo.py
  ush/ioda/bufr2ioda/marine/bufr2ioda_insitu_profiles_glider.py
  ush/ioda/bufr2ioda/marine/bufr2ioda_insitu_profiles_tesac.py
  ush/ioda/bufr2ioda/marine/bufr2ioda_insitu_profiles_xbtctd.py
  ush/ioda/bufr2ioda/marine/bufr2ioda_insitu_surface_altkob.py
  ush/ioda/bufr2ioda/marine/bufr2ioda_insitu_surface_trkob.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#1004 Bugfix on Broken GHRSST Ioda Converter
  utils/obsproc/Ghrsst2Ioda.h
  utils/test/prepdata.sh
  utils/test/testdata/ghrsst_sst_ma_202103241540.cdl
  utils/test/testdata/ghrsst_sst_ma_202103241550.cdl
  utils/test/testinput/gdas_ghrsst2ioda.yaml
  utils/test/testref/ghrsst2ioda.test
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed
