Repository NOAA-EMC/GDASApp, pull requests merged in 2024-06, with the labels that each got.

#1167 Addition of "Convert to Structured Grid" to gdas
  mains/gdas.cc
Labels: hera-GW-RT-Passed

#1173 use role.jedipara for hera ci
  README.md
  ci/driver.sh
  ci/gw_driver.sh
  ci/hera.sh
Labels: hera-RT-Passed, hera-GW-RT-Passed

#1195 update soca scripts and tests to work with wxflow changes
  test/soca/socaincr2mom6.sh
  ush/soca/marine_recenter.py
  ush/soca/prep_ocean_obs.py
  ush/soca/prep_ocean_obs_utils.py
  ush/soca/run_jjobs.py
Labels: hera-GW-RT-Running
