Repository NOAA-EMC/GDASApp, pull requests merged in 2024-02, with the labels that each got.

#878 copy subsampled marine BUFR to DMPDIR
  parm/soca/obs/config/insitu_profile_bathy.yaml
  parm/soca/obs/config/insitu_profile_tesac.yaml
  parm/soca/obs/config/insitu_surface_trkob.yaml
  parm/soca/obs/obs_list.yaml
  parm/soca/obsprep/obsprep_config.yaml
  scripts/exglobal_prep_ocean_obs.py
  test/soca/gw/setup_obsprep.sh
Labels: soca, orion-GW-RT-Failed

#900 Added ObsType group variables to the adpupa prepbufr api
  ush/ioda/bufr2ioda/bufr2ioda_adpupa_prepbufr.py
Labels: gdas validation

#848 Add SNOCVR snow depth python api code to GDASApp
  parm/ioda/bufr2ioda/bufr2ioda_snocvr_bufr.json
  ush/ioda/bufr2ioda/bufr2ioda_snocvr_bufr.py
Labels: landDA, hera-GW-RT, orion-GW-RT-Passed, gdas validation

#924 Update to the bkg name convention
  parm/soca/berror/soca_ensb.yaml
  scripts/exgdas_global_marine_analysis_prep.py
  test/soca/gw/prep.sh
  test/soca/testinput/ens_handler.yaml
  ush/soca/run_jjobs.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Running

#933 Update nc suffix and bufr file path for atmospheric observation yamls and bufr2ioda converters
  parm/atm/obs/config/aircraft.yaml
  parm/atm/obs/config/amsua_n19.yaml
  parm/atm/obs/config/atms_n20.yaml
  parm/atm/obs/config/atms_npp.yaml
  parm/atm/obs/config/cris-fsr_n20.yaml
  parm/atm/obs/config/cris-fsr_npp.yaml
  parm/atm/obs/config/gnssro.yaml
  parm/atm/obs/config/iasi_metop-a.yaml
  parm/atm/obs/config/iasi_metop-b.yaml
  parm/atm/obs/config/lgetkf_amsua_n19.yaml
  parm/atm/obs/config/lgetkf_sondes.yaml
  parm/atm/obs/config/omi_aura.yaml
  parm/atm/obs/config/ompsnp_npp.yaml
  parm/atm/obs/config/ompstc8_npp.yaml
  parm/atm/obs/config/satwind.yaml
  parm/atm/obs/config/satwind_ahi_h8.yaml
  parm/atm/obs/config/sfc.yaml
  parm/atm/obs/config/sfcship.yaml
  parm/atm/obs/config/sondes.yaml
  parm/atm/obs/config/ssmis_f17.yaml
  parm/atm/obs/config/ssmis_f18.yaml
  test/atm/global-workflow/config.atmanl
  test/atm/global-workflow/config.yaml
  test/atm/global-workflow/jjob_ens_init.sh
  test/atm/global-workflow/jjob_var_init.sh
  ush/ioda/bufr2ioda/bufr2ioda_acft_profiles_prepbufr.py
  ush/ioda/bufr2ioda/bufr2ioda_adpsfc_prepbufr.py
  ush/ioda/bufr2ioda/bufr2ioda_conventional_prepbufr_ps.py
  ush/ioda/bufr2ioda/bufr2ioda_sfcshp_prepbufr.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#934 Add 'bundle' directory and make Hera not download CRTM coeffs
  .gitignore
  build.sh
  bundle/CMakeLists.txt
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#910 IODA converters feature observation redating and error amplification
  utils/obsproc/Ghrsst2Ioda.h
  utils/obsproc/Rads2Ioda.h
  utils/obsproc/util.h
  utils/test/testdata/rads_adt_3a_2021181.cdl
  utils/test/testdata/rads_adt_3b_2021181.cdl
  utils/test/testinput/gdas_ghrsst2ioda.yaml
  utils/test/testinput/gdas_icecamsr2ioda.yaml
  utils/test/testinput/gdas_rads2ioda.yaml
  utils/test/testinput/gdas_smap2ioda.yaml
  utils/test/testinput/gdas_smos2ioda.yaml
  utils/test/testref/rads2ioda.test
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#940 ocn to ocean
  scripts/exgdas_global_marine_analysis_prep.py
  test/soca/gw/run_jjobs.yaml.test
Labels: hera-GW-RT-Passed, hera-GW-RT-Running, orion-GW-RT-Running
