Repository NOAA-EMC/GDASApp, pull requests merged in 2024-01, with the labels that each got.

#836 Remove tests with R2D2 and anything referencing it
  .github/workflows/unittests.yaml
  modulefiles/GDAS/hera.lua
  modulefiles/GDAS/orion.lua
  parm/soca/obs/obs_list_small.yaml
  parm/soca/obsproc/obs_list_obsproc.yaml
  parm/templates/stage.yaml
  scripts/exgdas_global_marine_analysis_prep.py
  scripts/exglobal_prep_ocean_obs.py
  test/atm/CMakeLists.txt
  test/atm/test_store_gsi_satbias.py
  test/soca/CMakeLists.txt
  test/soca/create_obsdb.py
  test/soca/gw/CMakeLists.txt
  test/soca/gw/run_jjobs.yaml.test
  test/soca/gw/test_concatioda.py
  test/soca/testdata/adt.nc.cdl
  test/soca/testdata/icec.nc.cdl
  test/soca/testdata/prof.nc.cdl
  test/soca/testdata/sss.nc.cdl
  test/soca/testdata/sst.nc.cdl
  ush/examples/run_scripts/soca025.yaml
  ush/r2d2/example_store_bkg.py
  ush/r2d2/proc_ops2r2d2.sh
  ush/r2d2/r2d2_store.py
  ush/soca/examples/run_jjobs_hera.yaml
  ush/soca/examples/run_jjobs_hera_025.yaml
  ush/ufsda/__init__.py
  ush/ufsda/archive.py
  ush/ufsda/post.py
  ush/ufsda/r2d2.py
  ush/ufsda/stage.py
Labels: hera-GW-RT-Failed

#851 Using diffusion central block
  parm/soca/berror/old/soca_bump2d.yaml
  parm/soca/berror/old/soca_bump_split.yaml
  parm/soca/berror/saber_blocks.yaml
  parm/soca/berror/soca_parameters_diffusion_hz.yaml
  parm/soca/berror/soca_parameters_diffusion_vt.yaml
  parm/soca/berror/soca_setcorscales.yaml
  scripts/exgdas_global_marine_analysis_bmat.sh
  scripts/exgdas_global_marine_analysis_prep.py
Labels: hera-GW-RT-Passed

#856 Fix Marine VRFY Task in the SOCA ctests
  ush/eva/marine_eva_post.py
  ush/eva/marine_gdas_plots.yaml
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#858 Changes obsproc to obsprep within ocean obs prep task
  parm/soca/obsprep/obsprep_config.yaml
  parm/soca/obsproc/obsproc_config.yaml
  scripts/exglobal_prep_ocean_obs.py
  test/soca/gw/CMakeLists.txt
  test/soca/gw/run_jjobs.yaml.test
  test/soca/gw/setup_obsprep.sh
  ush/soca/prep_marine_obs.py
Labels: hera-GW-RT-Failed, orion-GW-RT-Failed

#867 update resdet and resens keywords in prototypes
  prototypes/configs/cp0.sh
  prototypes/gen_prototype.sh
Labels: orion-RT-Passed, hera-RT-Passed, hera-GW-RT-Failed, orion-GW-RT-Passed

#873 Add spack-stack/1.6.0 support
  modulefiles/GDAS/hera.lua
  modulefiles/GDAS/hercules.lua
  modulefiles/GDAS/orion.lua
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#882 Add facility to take obs from multiple dmpdir cycles, forward and back
  parm/soca/obs/obs_list.yaml
  parm/soca/obsprep/obsprep_config.yaml
  scripts/exglobal_prep_ocean_obs.py
  test/soca/gw/prepdata.sh
  test/soca/gw/setup_obsprep.sh
  test/soca/testdata/gdas.20180414/00/ocean/adt/rads_adt_3a_2018104.cdl
  test/soca/testdata/gdas.20180414/00/ocean/adt/rads_adt_c2_2018104.cdl
  test/soca/testdata/gdas.20180414/00/ocean/adt/rads_adt_j2_2018104.cdl
  test/soca/testdata/gdas.20180414/00/ocean/adt/rads_adt_j3_2018104.cdl
  test/soca/testdata/gdas.20180414/00/ocean/adt/rads_adt_sa_2018104.cdl
  test/soca/testdata/gdas.20180414/12/ocean/sst/20180414092000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180414/18/ocean/sst/20180414150000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180414/18/ocean/sst/20180414151000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180414/18/ocean/sst/20180414152000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/00/ocean/adt/rads_adt_3a_2018105.cdl
  test/soca/testdata/gdas.20180415/00/ocean/adt/rads_adt_c2_2018105.cdl
  test/soca/testdata/gdas.20180415/00/ocean/adt/rads_adt_j2_2018105.cdl
  test/soca/testdata/gdas.20180415/00/ocean/adt/rads_adt_j3_2018105.cdl
  test/soca/testdata/gdas.20180415/00/ocean/adt/rads_adt_sa_2018105.cdl
  test/soca/testdata/gdas.20180415/00/ocean/sst/20180414210000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/00/ocean/sst/20180414211000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/00/ocean/sst/20180414212000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/06/ocean/sst/20180415030000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/06/ocean/sst/20180415031000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/06/ocean/sst/20180415032000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/12/ocean/adt/rads_adt_3a_2018105.cdl
  test/soca/testdata/gdas.20180415/12/ocean/adt/rads_adt_3b_2018105.cdl
  test/soca/testdata/gdas.20180415/12/ocean/icec/icec_amsr2_north_1.cdl
  test/soca/testdata/gdas.20180415/12/ocean/icec/icec_amsr2_north_2.cdl
  test/soca/testdata/gdas.20180415/12/ocean/icec/icec_amsr2_south_1.cdl
  test/soca/testdata/gdas.20180415/12/ocean/icec/icec_amsr2_south_2.cdl
  test/soca/testdata/gdas.20180415/12/ocean/sst/20180415090000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/12/ocean/sst/20180415091000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/12/ocean/sst/20180415092000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/12/ocean/sst/20180415095000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/12/ocean/sst/20180415114000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/12/ocean/sst/20180415132000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/18/ocean/sst/20180415150000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/18/ocean/sst/20180415151000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  test/soca/testdata/gdas.20180415/18/ocean/sst/20180415152000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.cdl
  ush/soca/prep_marine_obs.py
  utils/obsproc/Ghrsst2Ioda.h
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#888 Runs netcdf ioda converters in parallel
  scripts/exglobal_prep_ocean_obs.py
  ush/soca/run_jjobs.py
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed
