Repository NOAA-EMC/GDASApp, pull requests merged in 2025-05, with the labels that each got.

#1652 Renames ensemble statistics files
  ush/soca/marine_recenter.py
Labels: hera-GW-RT-Passed

#1643 Change COM_* to COMIN_*/COMOUT_*
  parm/aero/jcb-base.yaml.j2
  parm/atm/jcb-base.yaml.j2
  parm/ioda/bufr2ioda/bufr2ioda_acft_profiles_prepbufr.json
  parm/ioda/bufr2ioda/bufr2ioda_adpsfc_prepbufr.json
  parm/ioda/bufr2ioda/bufr2ioda_adpupa.json
  parm/ioda/bufr2ioda/bufr2ioda_adpupa_prepbufr.json
  parm/ioda/bufr2ioda/bufr2ioda_altkob_surface.json
  parm/ioda/bufr2ioda/bufr2ioda_atms.yaml
  parm/ioda/bufr2ioda/bufr2ioda_bathythermal_profiles.json
  parm/ioda/bufr2ioda/bufr2ioda_conventional_prepbufr_ps.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro_cosmic2.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro_geoopt.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro_grace.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro_k5.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro_metop.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro_paz.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro_piq.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro_s6.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro_spire.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro_tdm.json
  parm/ioda/bufr2ioda/bufr2ioda_gnssro_tsx.json
  parm/ioda/bufr2ioda/bufr2ioda_gsrcsr.json
  parm/ioda/bufr2ioda/bufr2ioda_iasi.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_argo.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_bathy.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_glider.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_tesac.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_tropical.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_tropical.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_xbtctd.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_salt_profile_argo.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_drifter.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_drifter.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_trkob.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_temp_profile_argo.yaml
  parm/ioda/bufr2ioda/bufr2ioda_ozone_omi.json
  parm/ioda/bufr2ioda/bufr2ioda_ozone_ompsnp.json
  parm/ioda/bufr2ioda/bufr2ioda_ozone_ompstc.json
  parm/ioda/bufr2ioda/bufr2ioda_satwind_scat.json
  parm/ioda/bufr2ioda/bufr2ioda_satwnd_amv_ahi.json
  parm/ioda/bufr2ioda/bufr2ioda_satwnd_amv_avhrr.json
  parm/ioda/bufr2ioda/bufr2ioda_satwnd_amv_goes.json
  parm/ioda/bufr2ioda/bufr2ioda_satwnd_amv_leogeo.json
  parm/ioda/bufr2ioda/bufr2ioda_satwnd_amv_modis.json
  parm/ioda/bufr2ioda/bufr2ioda_satwnd_amv_seviri.json
  parm/ioda/bufr2ioda/bufr2ioda_satwnd_amv_viirs.json
  parm/ioda/bufr2ioda/bufr2ioda_sevcsr.json
  parm/ioda/bufr2ioda/bufr2ioda_sfcshp_prepbufr.json
  parm/ioda/bufr2ioda/bufr2ioda_snocvr_bufr.json
  test/aero/global-workflow/jjob_var_final.sh
  test/aero/global-workflow/jjob_var_init.sh
  test/atm/global-workflow/jjob_ens_init.sh
  test/atm/global-workflow/jjob_ens_init_split.sh
  test/atm/global-workflow/jjob_var_init.sh
  ush/ioda/bufr2ioda/run_bufr2ioda.py
  ush/soca/prep_ocean_obs.py
  ush/soca/prep_ocean_obs_utils.py
Labels: orion-GW-RT-Passed

#1686 implement dbuoy surface converter + fix ocean basin bug
  test/marine/CMakeLists.txt
  test/marine/testinput/bufr2ioda_insitu_surface_dbuoyb_2019010700.yaml.in
  test/marine/testref/bufr2ioda_insitu_surface_dbuoyb_2019010700.ref
  ush/ioda/bufr2ioda/marine/b2i/b2iconverter/ocean.py
  ush/ioda/bufr2ioda/marine/b2i/b2iconverter/util.py
  ush/ioda/bufr2ioda/marine/b2i/bufr2ioda_insitu_surface_dbuoyb.py
  ush/ioda/bufr2ioda/marine/b2i/dbuoyb_surface_ioda_variables.py
Labels: hera-GW-RT-Passed

#1693 update parm/config path
  prototypes/gen_prototype.sh
  test/aero/global-workflow/jjob_var_init.sh
  test/aero/global-workflow/setup_workflow_exp.sh
  test/atm/global-workflow/jjob_ens_init.sh
  test/atm/global-workflow/jjob_ens_init_split.sh
  test/atm/global-workflow/jjob_var_init.sh
  test/atm/global-workflow/setup_workflow_exp.sh
  test/setup_workflow_exp.sh
  ush/soca/run_jjobs.py
Labels: hera-GW-RT-Passed

#1702 Update land-jediincr namelists
  parm/snow/apply_incr_nml.j2
  test/snow/apply_jedi_incr.sh
Labels: hercules-RT
