Repository NOAA-EMC/GDASApp, pull requests merged in 2025-02, with the labels that each got.

#1483 marine vrfy bugfix
  utils/soca/fig_gallery/vrfy_script.py
Labels: bug, soca

#1478 Add sea ice recentering
  parm/soca/berror/soca_ensrecenter.yaml
  ush/soca/marine_recenter.py
  utils/soca/gdas_ens_handler.h
Labels: hercules-GW-RT-Passed

#1472 IODA Converter with In-Situ Observations Concatenation and ObsError Inflation
  utils/obsproc/InsituAll2ioda.h
  utils/obsproc/Rads2Ioda.h
  utils/obsproc/applications/gdas_obsprovider2ioda.h
  utils/obsproc/util.h
  utils/test/CMakeLists.txt
  utils/test/prepdata.sh
  utils/test/testdata/insitu_profile_argo_1.cdl
  utils/test/testdata/insitu_profile_argo_2.cdl
  utils/test/testinput/gdas_insituall2ioda.yaml
  utils/test/testref/insituall2ioda.test
Labels: hercules-GW-RT-Passed

#1499 Removal of the marine verification tools
  ush/eva/marine_eva_post.py
  ush/eva/marine_gdas_plots.yaml
  ush/soca/soca_vrfy.py
  utils/soca/fig_gallery/README.md
  utils/soca/fig_gallery/gdassoca_obsstats.py
  utils/soca/fig_gallery/gdassoca_obsstats_template.html
  utils/soca/fig_gallery/marine_vrfy_display/README
  utils/soca/fig_gallery/marine_vrfy_display/default.css
  utils/soca/fig_gallery/marine_vrfy_display/fonts.css
  utils/soca/fig_gallery/marine_vrfy_display/index_vrfy_marine.html
  utils/soca/fig_gallery/run_vrfy.py
  utils/soca/fig_gallery/vrfy_config.yaml
  utils/soca/fig_gallery/vrfy_jobcard.sh.j2
  utils/soca/fig_gallery/vrfy_script.py
Labels: hera-GW-RT-Passed

#1486 Add components to use jcb yamls for marine letkf job
  parm/soca/letkf/marine-jcb-lektf.yaml.j2
  test/gw-ci/CMakeLists.txt
Labels: hera-GW-RT-Passed

#1501 Add options to inflate the ensemble while recentering
  utils/soca/gdas_ens_handler.h
Labels: hera-GW-RT-Passed

#1504 Incorporate multi-cycle concatination and separation of variables in post-BUFR observations
  parm/ioda/bufr2ioda/bufr2ioda_insitu_salt_profile_argo.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_temp_profile_argo.yaml
  parm/soca/obs/config/insitu_salt_profile_argo.yaml
  parm/soca/obs/config/insitu_temp_profile_argo.yaml
  parm/soca/obs/obs_list.yaml
  parm/soca/obsprep/obsprep_config.yaml
  ush/ioda/bufr2ioda/marine/b2i/bufr2ioda_insitu_salt_profile_argo.py
  ush/ioda/bufr2ioda/marine/b2i/bufr2ioda_insitu_temp_profile_argo.py
  ush/soca/prep_ocean_obs.py
  ush/soca/prep_ocean_obs_utils.py
Labels: hera-GW-RT-Passed

#1516 correct logic for upper loop limit in chem_diagb
  utils/chem/chem_diagb.h
Labels: hera-GW-RT-Passed

#1512 Minor build and install updates and ctest cleanup
  build.sh
  modulefiles/GDAS/wcoss2.intel.lua
  test/CMakeLists.txt
Labels: orion-GW-RT-Passed, hercules-GW-RT-Passed

#1517 Save marine background and analysis spread
  parm/soca/letkf/letkf_save.yaml.j2
Labels: hera-GW-RT-Passed
