Repository NOAA-EMC/GDASApp, pull requests merged in 2025-03, with the labels that each got.

#1511 Marine in situ obs update (SSS, moorings, drifters)
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_tropical.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_tropical.yaml
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_drifter.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_drifter.yaml
  parm/soca/obs/config/insitu_profile_tropical.yaml
  parm/soca/obs/config/insitu_surface_drifter.yaml
  parm/soca/obs/config/sss_smap_l2.yaml
  parm/soca/obs/config/sss_smos_l2.yaml
  parm/soca/obs/obs_list.yaml
  parm/soca/obsprep/obsprep_config.yaml
Labels: soca

#1526 tools for phase3 validation
  ush/ufoeval/README_phase3
  ush/ufoeval/config_gsi.yaml
  ush/ufoeval/config_jedi.yaml
  ush/ufoeval/setup_phase3.py
Labels: hera-GW-RT-Passed

#1546 patch for automated GDASApp CI to workaround g-w directory check
  test/gw-ci/create_exp.sh
Labels: hera-GW-RT-Running, hercules-GW-RT-Running

#1554 apply ci path patch only when running g-w ctests
  ci/run_ci.sh
Labels: orion-RT-Passed, hera-RT-Passed, hercules-RT-Passed

#1558 Bugfix ocean ensemble recentering
  utils/soca/gdas_ens_handler.h
Labels: hera-GW-RT-Passed, hercules-GW-RT-Passed

#1560 Bugfix SSS obs for LETKF
  parm/soca/obs/config/sss_smap_l2.yaml
  parm/soca/obs/config/sss_smos_l2.yaml
Labels: hercules-GW-RT-Passed

#1550 Bugfix/ocn ecen
  ush/soca/marine_recenter.py
Labels: hera-GW-RT-Passed, DO NOT MERGE, hercules-GW-RT-Passed

#1552 Add hybrid 4denvar as phase3 validation configuration
  ush/ufoeval/README_phase3
  ush/ufoeval/config_gsi.yaml
  ush/ufoeval/config_jedi.yaml
  ush/ufoeval/setup_phase3.py
Labels: orion-RT-Passed, hera-RT-Passed, hercules-RT-Passed

#1564 Removes obsolete json files from marine bufr2ioda
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_argo.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_bathy.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_dbuoy.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_dbuoyb.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_glider.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_marinemammals.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_mbuoy.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_mbuoyb.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_tesac.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_profile_xbtctd.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_altkob.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_ships.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_shipsu.json
  parm/ioda/bufr2ioda/bufr2ioda_insitu_surface_trkob.json
  parm/ioda/bufr2ioda/bufr2ioda_subpfl_argo_profiles.json
  parm/ioda/bufr2ioda/bufr2ioda_subpfl_glider_profiles.json
  parm/ioda/bufr2ioda/bufr2ioda_tesac_mammals_profiles.json
  parm/ioda/bufr2ioda/bufr2ioda_tesac_profiles.json
  parm/ioda/bufr2ioda/bufr2ioda_trackob_surface.json
  parm/ioda/bufr2ioda/bufr2ioda_xbtctd_profiles.json
Labels: soca, hera-GW-RT-Passed

#1566 Save LETKF mean analysis and mean increment for verification
  parm/soca/letkf/letkf_save.yaml.j2
Labels: hera-GW-RT-Passed, hercules-GW-RT-Passed

#1565 Fixing window_begin and end in yaml for redating ADT
  ush/soca/prep_ocean_obs.py
Labels: hera-GW-RT-Passed, hercules-GW-RT-Failed

#1569 Update OCEAN_BASIN_FILE_ORION for marine ctest (#1568)
  test/marine/CMakeLists.txt
Labels: orion-GW-RT-Passed

#1570 added original date
  utils/obsproc/NetCDFToIodaConverter.h
  utils/obsproc/util.h
  utils/test/testref/insituall2ioda.test
  utils/test/testref/rads2ioda.test
Labels: hera-GW-RT-Passed
