Repository NOAA-EMC/GDASApp, pull requests merged in 2025-01, with the labels that each got.

#1423 Add observation window to Argo float obs and other BUFR-sourced obs
  parm/soca/obsprep/obsprep_config.yaml
  ush/soca/prep_ocean_obs.py
  ush/soca/prep_ocean_obs_utils.py
Labels: hera-GW-RT-Passed

#1435 Update wcoss2.intel.lua to spack-stack
  modulefiles/GDAS/wcoss2.intel.lua
  test/gw-ci/create_exp.sh
  ush/module-setup.sh
Labels: hera-GW-RT-Passed, orion-GW-RT-Passed

#1434 clean up stable_driver.sh
  ci/run_ci.sh
  ci/stable_driver.sh
Labels: hercules-GW-RT-Running

#1440 double ci ctest timeout
  ci/run_ci.sh
Labels: hercules-GW-RT-Passed

#1464 Update marine vrfy HTML codes
  utils/soca/fig_gallery/marine_vrfy_display/default.css
  utils/soca/fig_gallery/marine_vrfy_display/index_vrfy_marine.html
Labels: soca

#1471 update spack-stack path in Hera modulefiles
  modulefiles/EVA/hera.lua
  modulefiles/GDAS/hera.intel.lua
Labels: hera-GW-RT-Passed
